def hesapMakinesi():
  print("\33[1;32;40m")
  print("╔══════════════════════════╗")
  print("║\033[31m   Hesap Makinesi       \33[0m\33[1;32;40m  ║")
  print("║                          ║")
  print("║   1-) Toplama İşlemi     ║")
  print("║   2-) Çıkarma İşlemi     ║")
  print("║   3-) Çarpma İşlemi      ║")
  print("║   4_) Bölme İşlemi       ║")
  print("║                          ║")
  print("║                          ║")
  print("║   Seçiminizi yapınız     ║")
  print("╚══════════════════════════╝")
  secim = input("Seciminizi yapınız:")
  if secim == "1": 
   print("Toplama işlemini seçtiniz")
   sayi1= int(input("1. sayıyı giriniz:"))
   sayi2= int(input("2. sayıyı giriniz:"))
   print("Toplam:", sayi1 + sayi2)
  if secim == "2": 
   print("Çıkarma işlemini seçtiniz")
   sayi1= int(input("1. sayıyı giriniz:"))
   sayi2= int(input("2. sayıyı giriniz:"))
   print("Fark:", sayi1 - sayi2)
  if secim == "3":
   print("Çarpma işlemini seçtiniz")
   sayi1= int(input("1. sayıyı giriniz:"))
   sayi2= int(input("2. sayıyı giriniz:"))
   print("Çarpım:", sayi1 * sayi2)
  if secim == "4":
   print("Bölme işlemini seçtiniz")
   sayi1= int(input("1. sayıyı giriniz:"))
   sayi2= int(input("2. sayıyı giriniz:"))
   print("Bölüm:", sayi1 / sayi2)  
